apiVersion: apps/v1
kind: Deployment
metadata:
  name: seiodck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seiodck
  template:
    metadata:
      labels:
        app: seiodck
    spec:
      containers:
      - image: okteto.dev/seiodck:latest
        name: seiodck
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "71f7bda5-5bf6-4e04-8c9b-f820abd6bdf2"
        - name: Vless_Path
          value: "/71f7bda5-5bf6-4e04-8c9b-f820abd6bdf2-vless"
        - name: Vmess_UUID
          value: "71f7bda5-5bf6-4e04-8c9b-f820abd6bdf2"
        - name: Vmess_Path
          value: "/8f4d4709-e41d-4954-8213-6dfce57e72b3-vmess"
        - name: Share_Path
          value: "$Share_Path"
